name: Website Carbon API check 🌱

on: [push]

jobs:
  website_carbon_job:
    runs-on: ubuntu-latest
    name: A job to call website carbon api
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Fetch Website Carbon data
        uses: ./ # Uses an action in the root directory
        id: api
        with:
          url: "https%3A%2F%2Fkmaaallen.github.io%2Fgraphql-pokemon%2F"
      # Use the output from the `hello` step
      - name: Get the API output
        run: echo "The returned response is ${{ steps.api.outputs.stats }}"
